version: "3"

services:
  obspi:
    container_name: "obspi"
    image: "ghcr.io/sdsobservatory/obspi:main"
    restart: unless-stopped
    pull_policy: always
    ports:
      - "8080:80"
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    env_file:
      - variables.env
